Python/BookReviews/apps/first_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^process/(?P<route>\w+)$', views.process, name = "process"),
    url(r'^logout$', views.logout, name = "logout"),
]

Python/BookReviews/apps/reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # http://localhost:8000/bookreviews/..
    url(r'^$', views.index, name = "mainpage"),
    url(r'^newreview$', views.add_review, name = "add_review"),
    url(r'^createreview$', views.create_review, name = "create_review"),
    url(r'^showreview$', views.show_review, name = "show_review"),
]

Python/BookReviews/main/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include("apps.first_app.urls", namespace="login")),
    url(r'^bookreviews/', include("apps.reviews.urls", namespace="reviews")),
]

Python/BookReviews/apps/first_app/models.py
from __future__ import unicode_literals
from django.db import models
import os, binascii, bcrypt

class UserManager(models.Manager):
    def validateUser(self, postData):
        errorStr = []
        if len(postData['name']) < 3:
            errorStr.append("First name can't be less than 3 characters")
        if len(postData['username']) < 3:
            errorStr.append("Username can't be less than 3 characters")
        if User.object.filter(username=postData['username']):
            errorStr.append("Username is already registered")
        if len(postData["password"]) < 8:
            errorStr.append("Password must be at least 8 characters")
        if postData["password"] != postData["pw_confirm"]:
            errorStr.append("Password didn't match confirmation.")

        # create hashing
        encrypted_pw = bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt())

        response_to_views = {}
        if errorStr:
            response_to_views['status'] = False
            response_to_views['errorStr'] = errorStr
        else:
            user = self.create(name = postData["name"], username = postData["username"], password = encrypted_pw)
            response_to_views['status'] = True
            response_to_views['userobj'] = user
        return response_to_views

    def loginUser(self, postData):
        errorStr = []
        
        user = User.object.filter(username=postData['username'])
        if not user:
            errorStr.append("Invalid username")
        else: 
            if bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()) != user[0].password:
                errorStr.append("Password is incorrect.")
        response_to_views = {}
        if errorStr:
            response_to_views['status'] = False
            response_to_views['errorStr'] = errorStr
        else: 
            response_to_views['status'] = True
            response_to_views['userobj'] = user[0]
        return response_to_views

class User(models.Model):
  name = models.TextField(max_length=100)
  username = models.TextField(max_length=100)
  password = models.TextField(max_length=100)
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)
  object = UserManager()
  def __str__(self):
    return self.name

Python/BookReviews/apps/reviews/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..first_app.models import User

# Create your models here.

class BookManager(models.Manager):
    def createBook(self, postData):
        errorStr = []
        if len(postData['book_title']) < 1:
            errorStr.append("Book title cannot be empty")
        if len(postData['author']) < 1:
            errorStr.append("Author cannot be empty")
        
        response_to_views = {}
        if errorStr:
            response_to_views['status'] = False
            response_to_views['errorStr'] = errorStr
        else:
            book = self.create(book_title = postData["book_title"], author = postData["author"])
            response_to_views['status'] = True
            response_to_views['book_obj'] = book
        return response_to_views


class ReviewManager(models.Manager):
    def createReview(self, postData, user_id):
        errorStr = []
        if len(postData['review']) < 1:
            errorStr.append("Review can't be empty")
        
        response_to_views = {}
        if errorStr:
            response_to_views['status'] = False
            response_to_views['errorStr'] = errorStr
        else:
            review = self.create(book = Book.objects.get(book_title=postData["book_title"]), review = postData["review"], rating = postData["rating"], reviewedby = User.object.get(id=user_id))
            response_to_views['status'] = True
            response_to_views['review_obj'] = review
        return response_to_views

class Book(models.Model):
  book_title = models.TextField(max_length=100)
  author = models.TextField(max_length=100)
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)
  objects = BookManager()
  def __str__(self):
    return self.book_title

class Review(models.Model):
  book = models.ForeignKey(Book, related_name="review")
  review = models.TextField(max_length=100)
  rating = models.TextField(max_length=100)
  reviewed_by = models.ForeignKey(User, related_name="book_review")
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)
  def __str__(self):
    return self.book

Python/BookReviews/apps/first_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages


def index(request): 
	return render(request, "first_app/index.html")

def process(request, route):
	if request.method == "POST":
		# this brings in the value of response_to_views
		if route == "register":
			response_from_models = User.object.validateUser(request.POST)
		else:
			response_from_models = User.object.loginUser(request.POST)
		if not response_from_models["status"]:
			for error in response_from_models["errorStr"]:
				messages.error(request, error)
			return redirect("login:index")
	print "*"*20
	print response_from_models["userobj"].id
	request.session["user_id"] = response_from_models["userobj"].id
	print request.session["user_id"]
	return redirect("reviews:mainpage")

def logout(request):
	request.session.flush()
	return redirect("login:index")

Python/BookReviews/apps/reviews/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Book, Review
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, "reviews/mainpage.html")

def add_review(request):
    return render(request, "reviews/add_review.html")

def create_review(request):
    if request.method == "POST":
        response_from_book_models = Book.objects.createBook(request.POST)
        response_from_review_models = Review.objects.createReview(request.POST, request.session["user_id"])
        if not response_from_book_models["status"]:
            for error in response_from_models["errorStr"]:
                messages.error(request, error)
        if not response_from_review_models["status"]:
            for error in response_from_models["errorStr"]:
                messages.error(request, error)
        return redirect("reviews:add_review")
    return redirect("reviews:show_review")

def show_review(request):
    return render(request, "reviews/show_review.html")

Python/BookReviews/apps/first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
    </head>
    <body>
    <h1>Welcome!</h1>
    <div>
        {% for message in messages %}
        <p>{{ message }}<p>
        {% endfor %}
    </div>
    <fieldset>
    <legend>Register</legend>  
    <form action='{% url "login:process" route="register" %}' method='post'>
        {% csrf_token %}
        <label for='name'>Name:</label>
        <input type='text' id='name' name='name'><br>
        <label for='username'>Username:</label>
        <input type='text' id='username' name='username'><br>
        <label for='password'>Password:</label>
        <input type='password' id='password' name='password'><br>
        <label for='pw_confirm'>Confirmation:</label>
        <input type='password' for='pw_confirm' name='pw_confirm'>
        <p>* password should be at least 8 characters long</p>
        <input type='submit' value='Register'>
    </form>
    </fieldset>
    <fieldset>
    <legend>Login</legend>   
    <form action='{% url "login:process" route="login" %}' method='post'>
        {% csrf_token %}
        <label for='username'>Username:</label>
        <input type='text' id='username' name='username'><br>
        <label for='password'>Password:</label>
        <input type='password' id='password' name='password'>
        <input type='submit' value='Login'>
    </form>   
    </fieldset>
    </body>
</html>

Python/BookReviews/apps/reviews/templates/reviews/add_review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
    </head>
    <body>
        <h1>Add a New Book and a Review:</h1>

         {% for message in messages %}
        <p>{{ message }}<p>
        {% endfor %}

        <fieldset>
        <legend>no-poo</legend>
        <form action='{% url "reviews:create_review" %}' method='post'>
            {% csrf_token %}
            <label for='book_title'>Book Title:</label>
            <input type='text' id='book_title' name='book_title'><p></p>
            <label for='author'>Author:</label>
            <input type='text' id='author' name='author'><p></p>
            <label for='review'>Review:</label>
            <textarea name='review'></textarea><p></p>
            Rating: <select name='Rating'>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select><p></p>
            <input type='submit' value='Submit'>
        </form>
        </fieldset>
    </body>
</html>

Python/BookReviews/apps/reviews/templates/reviews/mainpage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
    </head>
    <body>
        <h1>Hello, World!</h1>
        <a href="{% url 'reviews:add_review' %}">Add a book and review!</a>
    </body>
</html>

Python/BookReviews/apps/reviews/templates/reviews/show_review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
    </head>
    <body>
        <h1>You reviewed a book! Gerd jerb!</h1>
    </body>
</html>